import os

async def export_to_docs(story) -> str:
    creds_json = os.environ.get("GOOGLE_OAUTH_CREDENTIALS_JSON")
    if creds_json and creds_json.strip() not in ("", "{}"):
        return await _export_google_docs(story)
    return await export_to_docs_local(story)

async def export_to_docs_local(story) -> str:
    lines = [f"# LORE Study Guide: {story.topic}\n\n",
             f"*Generated by LORE — Live, Orchestrated, Reactive Encyclopaedia*\n\n",
             "---\n\n"]
    for chapter in story.chapters:
        lines.append(f"## Chapter {chapter.index + 1}: {chapter.title}\n\n")
        lines.append(f"{chapter.narration_script}\n\n")
        if chapter.pins:
            lines.append("**Explore deeper:**\n\n")
            for pin in chapter.pins:
                lines.append(f"- **{pin.label}**: {pin.teaser}\n")
            lines.append("\n")
    lines.append("---\n\n## Key Concepts\n\n")
    for ch in story.chapters:
        for pin in ch.pins:
            lines.append(f"**{pin.label}**: {pin.teaser}\n\n")

    os.makedirs("exports", exist_ok=True)
    path = f"exports/lore_guide_{story.id}.md"
    with open(path, "w") as f:
        f.writelines(lines)
    return f"/exports/{story.id}/docs"

async def _export_google_docs(story) -> str:
    return await export_to_docs_local(story)
