import os
import io
import base64
import asyncio
from docx import Document
from docx.shared import Inches

async def export_to_docs(story) -> str:
    # Bypassing Google OAuth setup in favor of native .docx generation downloads
    return await export_to_docs_local(story)

async def export_to_docs_local(story) -> str:
    def _create_docx():
        doc = Document()
        doc.add_heading(f"LORE Study Guide: {story.topic}", 0)
        
        p = doc.add_paragraph()
        p.add_run("Generated by LORE — Live, Orchestrated, Reactive Encyclopaedia").italic = True
        
        for chapter in story.chapters:
            doc.add_heading(f"Chapter {chapter.index + 1}: {chapter.title}", level=2)
            
            if chapter.image_url and chapter.image_url.startswith("data:image"):
                try:
                    header, b64data = chapter.image_url.split(",", 1)
                    img_bytes = base64.b64decode(b64data)
                    img_stream = io.BytesIO(img_bytes)
                    doc.add_picture(img_stream, width=Inches(5))
                except Exception as e:
                    print("Error embedding image into DOCX:", e)
            
            doc.add_paragraph(chapter.narration_script)
            
            if chapter.pins:
                doc.add_heading("Explore deeper:", level=3)
                for pin in chapter.pins:
                    p = doc.add_paragraph(style='List Bullet')
                    p.add_run(f"{pin.label}: ").bold = True
                    p.add_run(pin.teaser)
                    
        doc.add_heading("Key Concepts Summary", level=1)
        for chapter in story.chapters:
            for pin in chapter.pins:
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(f"{pin.label}: ").bold = True
                p.add_run(pin.teaser)

        os.makedirs("exports", exist_ok=True)
        path = f"exports/lore_guide_{story.id}.docx"
        doc.save(path)
        return f"/exports/{story.id}/docs"
        
    return await asyncio.to_thread(_create_docx)
